### ISSUE TITLE
Question showing up in Option 1

### ISSUE THREAD

**Issue by MichaelJiangCS** [ultraviolet89/NBATriviaGame#2]
Hey Violetta, I fixed the code accordingly and the question is showing up in the Option1 button instead of the question textField, which took me back to the problem i had before making the changes, any idea why this is happening? Did you get it work on your end?
![issue](https://github.com/ultraviolet89/NBATriviaGame/assets/97463680/2fcc229a-4f61-41b4-b054-bf28311dc57b)

**Comment by ultraviolet89** [comment]
You are only querying the `Questions` table, and nowhere in the code are you retrieving data from the `Options` table. I raised this issue here: https://github.com/ultraviolet89/NBATriviaGame/issues/1#issuecomment-1849111493, but no one has responded yet.
By implementing a source for `Options`, you will likely uncover the reason why Questions are loading into the Option.

**Comment by ultraviolet89** [comment]
This is the Questions data query. where are the Options data coming from?
https://github.com/ultraviolet89/NBATriviaGame/blob/22ba9c7d522110b400c46e0f4355bbae6c67e988/app/src/main/java/com/violetta/nbatriviagame/model/QuestionRepository.kt#L17

**Comment by MichaelJiangCS** [comment]
> This is the Questions data query. where are the Options data coming from?
> 
> https://github.com/ultraviolet89/NBATriviaGame/blob/22ba9c7d522110b400c46e0f4355bbae6c67e988/app/src/main/java/com/violetta/nbatriviagame/model/QuestionRepository.kt#L17

The Option table is inside the same nba.db file, wtih a foreign key 'question_id' linked to the Question table.

**Comment by ultraviolet89** [comment]
I know where the data is, question I have where is the code querying for the data. You guys have a querying `Questions`, but not `Options` data.

**Comment by ultraviolet89** [comment]
Something like:
```kotlin
val questionId = questionsCursor.getInt(questionIdColumnIndex )
val optionsCursor = db.rawQuery("SELECT option_text FROM Options WHERE question_id = ?", arrayOf(questionId.toString()))
val options = mutableListOf<String>()
if (optionsCursor.moveToFirst()) {
	do {
		options.add(optionsCursor.getString(optionsCursor.getColumnIndex("option_text")))
	} while (optionsCursor.moveToNext())
}
optionsCursor.close()
```

**Comment by MichaelJiangCS** [comment]
yeah i get what you are saying now, im working on it

**Comment by ultraviolet89** [comment]
@MichaelJiangCS let me know if you get stuck

**Comment by ultraviolet89** [comment]
@MichaelJiangCS just in case you still having trouble, in your IDE when you mouse over this `Question` data class you should see explanation what it should have for properties. Ctrl+click on it, will get you to the code, where I wrote all the docs. 

https://github.com/ultraviolet89/NBATriviaGame/blob/22ba9c7d522110b400c46e0f4355bbae6c67e988/app/src/main/java/com/violetta/nbatriviagame/model/QuestionRepository.kt#L33

Current properties in the latest commit are invalid.

**Comment by MichaelJiangCS** [comment]
ok this is fixed
