### ISSUE TITLE
Options are not being read

### ISSUE THREAD

**Issue by MichaelJiangCS** [ultraviolet89/NBATriviaGame#3]
I did a few changes and now the questions are in the right place, just the options are not being read. Could you please take a look?@ultraviolet89 

In BaseTriviaActivity.kt I added a println(line 102) to see if there's anything in options and it turns out that options is empty..

**Comment by ultraviolet89** [comment]
Bro, leave the data class along, lol
https://github.com/ultraviolet89/NBATriviaGame/blob/dba15c4f02fe8bfe1156757e591268917be6717d/app/src/main/java/com/violetta/nbatriviagame/model/Question.kt#L13-L17
This class encapsulates all the data for a single trivia question, making it easier to manage and manipulate this data in other parts of the application.
This is exactly why I mentioned this in our other issue https://github.com/ultraviolet89/NBATriviaGame/issues/2#issuecomment-1850937920

All you had to do is to make sure the arguments passed to the `Questions` has matching properties.
`Question(questionId.toString(), listOf(questionText), answerText) ` you guys were passing `question id`, `question text`, and `answerText`, when it should be simply `Question(questionText, options, answerText)`.

Plus I kind of already wrote you sample few lines implementation in here: https://github.com/ultraviolet89/NBATriviaGame/issues/2#issuecomment-1850866609
So, basically all you had to do is to replace this:
https://github.com/ultraviolet89/NBATriviaGame/blob/dba15c4f02fe8bfe1156757e591268917be6717d/app/src/main/java/com/violetta/nbatriviagame/model/QuestionRepository.kt#L32-L34

with this

```kotlin
// Query to get options for this question
val optionsCursor = db.rawQuery("SELECT option_text FROM Options WHERE question_id = ?", arrayOf(questionId.toString()))
val options = mutableListOf<String>()

if (optionsCursor.moveToFirst()) {
    do {
        options.add(optionsCursor.getString(questionIdColumnIndex))
    } while (optionsCursor.moveToNext())
}
optionsCursor.close()

val question = Question(questionText, options, answerText) 
questions.add(question)

```
Only these change will produce our desired options:
![screenshot_2](https://github.com/ultraviolet89/NBATriviaGame/assets/122412716/b5a2b7a8-8307-4dd0-9718-45df62dbbfcd)

**Comment by MichaelJiangCS** [comment]
idk if i can delete my logic and work with your code again, do you want to commit and push your code?

**Comment by MichaelJiangCS** [comment]
like, my way works, it's just not reading the options correctly that i havent figured out why

**Comment by MichaelJiangCS** [comment]
so if you really dont want to share the code that's fine with me, we can all submit each other's version so we dont become a burden to you. As you said you had the whole structure done 1 week before the due date, and it would be not fair that you get points off becuase of us. You can submit your version since you have yours runing successfully.

**Comment by ultraviolet89** [comment]
@MichaelJiangCS I had to github massage things to override your changes. Try again, you should be able to see Options pulled along with question now.

**Comment by ultraviolet89** [comment]
We should of probably use branches, instead of pushing all in to the main
